/*
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Copyright (C) 1996-2002 Henrik Isaksson
 * Copyright (C) 2026 amigazen project
 *
 * pragma/popupmenu_lib.h - Generated by LibDescConverter from SFD
 */

#ifndef PRAGMA_POPUPMENU_LIB_H
#define PRAGMA_POPUPMENU_LIB_H

/*
** Aztec 'C', Maxon 'C' and StormC format pragma files
**
**
** Generated by LibDescConverter from an sfd file
*/

#ifndef CLIB_POPUPMENU_PROTOS_H
#include <clib/popupmenu_protos.h>
#endif /* CLIB_POPUPMENU_PROTOS_H */

/*"popupmenu.library" */
/*--- functions in V2 or higher --- */

/* Menu and item construction */

#pragma amicall(PopupMenuBase, 0x1E, PM_MakeMenuA(a1))
#if defined(__STORM__)
#pragma tagcall(PopupMenuBase, 0x1E, PM_MakeMenu(a1))
#endif /* __STORM__ */
#pragma amicall(PopupMenuBase, 0x24, PM_MakeItemA(a1))
#if defined(__STORM__)
#pragma tagcall(PopupMenuBase, 0x24, PM_MakeItem(a1))
#endif /* __STORM__ */
#pragma amicall(PopupMenuBase, 0x2A, PM_FreePopupMenu(a1))
#pragma amicall(PopupMenuBase, 0x30, PM_OpenPopupMenuA(a1,a2))
#if defined(__STORM__)
#pragma tagcall(PopupMenuBase, 0x30, PM_OpenPopupMenu(a1,a2))
#endif /* __STORM__ */
#pragma amicall(PopupMenuBase, 0x36, PM_MakeIDListA(a1))
#if defined(__STORM__)
#pragma tagcall(PopupMenuBase, 0x36, PM_MakeIDList(a1))
#endif /* __STORM__ */
/*--- functions in V3 or higher --- */

/* Item query and attributes */

#pragma amicall(PopupMenuBase, 0x3C, PM_ItemChecked(a1,d1))
#pragma amicall(PopupMenuBase, 0x42, PM_GetItemAttrsA(a2,a1))
#if defined(__STORM__)
#pragma tagcall(PopupMenuBase, 0x42, PM_GetItemAttrs(a2,a1))
#endif /* __STORM__ */
#pragma amicall(PopupMenuBase, 0x48, PM_SetItemAttrsA(a2,a1))
#if defined(__STORM__)
#pragma tagcall(PopupMenuBase, 0x48, PM_SetItemAttrs(a2,a1))
#endif /* __STORM__ */
#pragma amicall(PopupMenuBase, 0x4E, PM_FindItem(a1,d1))
/*--- functions in V5 or higher --- */

/* State changes */

#pragma amicall(PopupMenuBase, 0x54, PM_AlterState(a1,a2,d1))
/*--- functions in V6 or higher --- */

/* Obsolete V6 FilterIMsg vector (returns NULL). Kept for FuncTab layout. */
/* Published client headers historically mis-labelled this bias as PM_FilterIMsgA; */
/* the real FilterIMsgA follows ExLstA below. */

#pragma amicall(PopupMenuBase, 0x60, PM_ExLstA(a1))
#if defined(__STORM__)
#pragma tagcall(PopupMenuBase, 0x60, PM_ExLst(a1))
#endif /* __STORM__ */
#pragma amicall(PopupMenuBase, 0x66, PM_FilterIMsgA(a0,a1,a2,a3))
#if defined(__STORM__)
#pragma tagcall(PopupMenuBase, 0x66, PM_FilterIMsg(a0,a1,a2,a3))
#endif /* __STORM__ */
/*--- functions in V8 or higher --- */

/* Dynamic menu editing */

#pragma amicall(PopupMenuBase, 0x6C, PM_InsertMenuItemA(a0,a1))
#if defined(__STORM__)
#pragma tagcall(PopupMenuBase, 0x6C, PM_InsertMenuItem(a0,a1))
#endif /* __STORM__ */
#pragma amicall(PopupMenuBase, 0x72, PM_RemoveMenuItem(a0,a1))
/*--- functions in V9 or higher --- */

/* Hooks, version, prefs, layout */

#pragma amicall(PopupMenuBase, 0x78, PM_AbortHook(a0))
#pragma amicall(PopupMenuBase, 0x7E, PM_GetVersion())
#pragma amicall(PopupMenuBase, 0x84, PM_ReloadPrefs())
#pragma amicall(PopupMenuBase, 0x8A, PM_LayoutMenuA(a0,a1,a2))
#if defined(__STORM__)
#pragma tagcall(PopupMenuBase, 0x8A, PM_LayoutMenu(a0,a1,a2))
#endif /* __STORM__ */

/* Private ARexx host vector (FuncTab placeholder; not for applications) */

/*--- functions in V10 or higher --- */
#pragma amicall(PopupMenuBase, 0x96, PM_FreeIDList(a0))

#endif /* PRAGMA_POPUPMENU_LIB_H */
