/*
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Copyright (C) 1996-2002 Henrik Isaksson
 * Copyright (C) 2026 amigazen project
 *
 * pragmas/popupmenu_pragmas.h - Generated by LibDescConverter from SFD
 */

#ifndef PRAGMAS_POPUPMENU_PRAGMAS_H
#define PRAGMAS_POPUPMENU_PRAGMAS_H

/*
** Lattice 'C', Aztec 'C', SAS/C and DICE format pragma files.
**
**
** Generated by LibDescConverter from an sfd file
*/

#ifndef CLIB_POPUPMENU_PROTOS_H
#include <clib/popupmenu_protos.h>
#endif /* CLIB_POPUPMENU_PROTOS_H */

/*"popupmenu.library" */
/*--- functions in V2 or higher --- */

/* Menu and item construction */

#pragma libcall PopupMenuBase PM_MakeMenuA 1E 901
#if defined(__SASC_60)
#pragma tagcall PopupMenuBase PM_MakeMenu 1E 901
#endif /* __SASC_60 */
#pragma libcall PopupMenuBase PM_MakeItemA 24 901
#if defined(__SASC_60)
#pragma tagcall PopupMenuBase PM_MakeItem 24 901
#endif /* __SASC_60 */
#pragma libcall PopupMenuBase PM_FreePopupMenu 2A 901
#pragma libcall PopupMenuBase PM_OpenPopupMenuA 30 A902
#if defined(__SASC_60)
#pragma tagcall PopupMenuBase PM_OpenPopupMenu 30 A902
#endif /* __SASC_60 */
#pragma libcall PopupMenuBase PM_MakeIDListA 36 901
#if defined(__SASC_60)
#pragma tagcall PopupMenuBase PM_MakeIDList 36 901
#endif /* __SASC_60 */
/*--- functions in V3 or higher --- */

/* Item query and attributes */

#pragma libcall PopupMenuBase PM_ItemChecked 3C 1902
#pragma libcall PopupMenuBase PM_GetItemAttrsA 42 9A02
#if defined(__SASC_60)
#pragma tagcall PopupMenuBase PM_GetItemAttrs 42 9A02
#endif /* __SASC_60 */
#pragma libcall PopupMenuBase PM_SetItemAttrsA 48 9A02
#if defined(__SASC_60)
#pragma tagcall PopupMenuBase PM_SetItemAttrs 48 9A02
#endif /* __SASC_60 */
#pragma libcall PopupMenuBase PM_FindItem 4E 1902
/*--- functions in V5 or higher --- */

/* State changes */

#pragma libcall PopupMenuBase PM_AlterState 54 1A903
/*--- functions in V6 or higher --- */

/* Obsolete V6 FilterIMsg vector (returns NULL). Kept for FuncTab layout. */
/* Published client headers historically mis-labelled this bias as PM_FilterIMsgA; */
/* the real FilterIMsgA follows ExLstA below. */

#pragma libcall PopupMenuBase PM_ExLstA 60 901
#if defined(__SASC_60)
#pragma tagcall PopupMenuBase PM_ExLst 60 901
#endif /* __SASC_60 */
#pragma libcall PopupMenuBase PM_FilterIMsgA 66 BA9804
#if defined(__SASC_60)
#pragma tagcall PopupMenuBase PM_FilterIMsg 66 BA9804
#endif /* __SASC_60 */
/*--- functions in V8 or higher --- */

/* Dynamic menu editing */

#pragma libcall PopupMenuBase PM_InsertMenuItemA 6C 9802
#if defined(__SASC_60)
#pragma tagcall PopupMenuBase PM_InsertMenuItem 6C 9802
#endif /* __SASC_60 */
#pragma libcall PopupMenuBase PM_RemoveMenuItem 72 9802
/*--- functions in V9 or higher --- */

/* Hooks, version, prefs, layout */

#pragma libcall PopupMenuBase PM_AbortHook 78 801
#pragma libcall PopupMenuBase PM_GetVersion 7E 00
#pragma libcall PopupMenuBase PM_ReloadPrefs 84 00
#pragma libcall PopupMenuBase PM_LayoutMenuA 8A A9803
#if defined(__SASC_60)
#pragma tagcall PopupMenuBase PM_LayoutMenu 8A A9803
#endif /* __SASC_60 */

/* Private ARexx host vector (FuncTab placeholder; not for applications) */

/*--- functions in V10 or higher --- */
#pragma libcall PopupMenuBase PM_FreeIDList 96 801

#endif /* PRAGMAS_POPUPMENU_PRAGMAS_H */
