/*
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Copyright (C) 1996-2002 Henrik Isaksson
 * Copyright (C) 2026 amigazen project
 *
 * proto/popupmenu.h - Generated by LibDescConverter from SFD
 */

#ifndef PROTO_POPUPMENU_H
#define PROTO_POPUPMENU_H

/*
** 'C' prototype and compiler specific header file combo
**
**
** Generated by LibDescConverter from an sfd file
*/

#ifdef _NO_INLINE

#include <clib/popupmenu_protos.h>

#else

#ifndef __NOLIBBASE__


#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif /* EXEC_LIBRARIES_H */

extern struct PopupMenuBase * PopupMenuBase;
#endif /* __NOLIBBASE__ */


#if defined(LATTICE) || defined(__SASC) || defined(_DCC)

#ifndef PRAGMAS_POPUPMENU_PRAGMAS_H
#include <pragmas/popupmenu_pragmas.h>
#endif /* PRAGMAS_POPUPMENU_PRAGMAS_H */


#elif defined(AZTEC_C) || defined(__MAXON__) || defined(__STORM__)

#ifndef PRAGMA_POPUPMENU_LIB_H
#include <pragma/popupmenu_lib.h>
#endif /* PRAGMA_POPUPMENU_LIB_H */

#elif defined(__VBCC__)

#include <clib/popupmenu_protos.h>

#ifndef INLINE_POPUPMENU_PROTOS_H
#include <inline/popupmenu_protos.h>
#endif /* INLINE_POPUPMENU_PROTOS_H */


#elif defined(__GNUC__)

#if defined(mc68000)
#ifndef INLINE_POPUPMENU_H
#include <inline/popupmenu.h>
#endif /* INLINE_POPUPMENU_H */
#else
#include <clib/popupmenu_protos.h>
#endif /* mc68000 */


/* Any other compiler */
#else

#include <clib/popupmenu_protos.h>


#endif /* __GNUC__ */


#endif /* _NO_INLINE */

#endif /* PROTO_POPUPMENU_H */
