/*
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Copyright (C) 1996-2002 Henrik Isaksson
 * Copyright (C) 2026 amigazen project
 *
 * inline/popupmenu_protos.h - Generated by LibDescConverter from SFD
 */

#ifndef INLINE_POPUPMENU_PROTOS_H
#define INLINE_POPUPMENU_PROTOS_H

/*
** VBCC format inline files.
**
**
** Generated by LibDescConverter from an sfd file
*/

/*"popupmenu.library" */
/*--- functions in V2 or higher --- */

/* Menu and item construction */

struct PopupMenu *__PM_MakeMenuA(__reg("a6") void *, __reg("a1") struct TagItem *tags)="\tjsr\t-30(a6)";
#define PM_MakeMenuA(tags) __PM_MakeMenuA(PopupMenuBase, (tags))

#if !defined(NO_INLINE_STDARG) && (__STDC__ == 1L) && (__STDC_VERSION__ >= 199901L)
struct PopupMenu *__PM_MakeMenu(__reg("a6") void *, ...)="\tmove.l\ta1,-(a7)\n\tlea\t4(a7),a1\n\tjsr\t-30(a6)\n\tmovea.l\t(a7)+,a1";
#define PM_MakeMenu(...) __PM_MakeMenu(PopupMenuBase, __VA_ARGS__)
#endif

struct PopupMenu *__PM_MakeItemA(__reg("a6") void *, __reg("a1") struct TagItem *tags)="\tjsr\t-36(a6)";
#define PM_MakeItemA(tags) __PM_MakeItemA(PopupMenuBase, (tags))

#if !defined(NO_INLINE_STDARG) && (__STDC__ == 1L) && (__STDC_VERSION__ >= 199901L)
struct PopupMenu *__PM_MakeItem(__reg("a6") void *, ...)="\tmove.l\ta1,-(a7)\n\tlea\t4(a7),a1\n\tjsr\t-36(a6)\n\tmovea.l\t(a7)+,a1";
#define PM_MakeItem(...) __PM_MakeItem(PopupMenuBase, __VA_ARGS__)
#endif

void __PM_FreePopupMenu(__reg("a6") void *, __reg("a1") struct PopupMenu *menu)="\tjsr\t-42(a6)";
#define PM_FreePopupMenu(menu) __PM_FreePopupMenu(PopupMenuBase, (menu))

ULONG __PM_OpenPopupMenuA(__reg("a6") void *, __reg("a1") struct Window *wnd, __reg("a2") struct TagItem *tags)="\tjsr\t-48(a6)";
#define PM_OpenPopupMenuA(wnd, tags) __PM_OpenPopupMenuA(PopupMenuBase, (wnd), (tags))

#if !defined(NO_INLINE_STDARG) && (__STDC__ == 1L) && (__STDC_VERSION__ >= 199901L)
ULONG __PM_OpenPopupMenu(__reg("a6") void *, __reg("a1") struct Window *wnd, ...)="\tmove.l\ta2,-(a7)\n\tlea\t4(a7),a2\n\tjsr\t-48(a6)\n\tmovea.l\t(a7)+,a2";
#define PM_OpenPopupMenu(...) __PM_OpenPopupMenu(PopupMenuBase, __VA_ARGS__)
#endif

struct PM_IDLst *__PM_MakeIDListA(__reg("a6") void *, __reg("a1") struct TagItem *tags)="\tjsr\t-54(a6)";
#define PM_MakeIDListA(tags) __PM_MakeIDListA(PopupMenuBase, (tags))

#if !defined(NO_INLINE_STDARG) && (__STDC__ == 1L) && (__STDC_VERSION__ >= 199901L)
struct PM_IDLst *__PM_MakeIDList(__reg("a6") void *, ...)="\tmove.l\ta1,-(a7)\n\tlea\t4(a7),a1\n\tjsr\t-54(a6)\n\tmovea.l\t(a7)+,a1";
#define PM_MakeIDList(...) __PM_MakeIDList(PopupMenuBase, __VA_ARGS__)
#endif

/*--- functions in V3 or higher --- */

/* Item query and attributes */

BOOL __PM_ItemChecked(__reg("a6") void *, __reg("a1") struct PopupMenu *pm, __reg("d1") ULONG id)="\tjsr\t-60(a6)";
#define PM_ItemChecked(pm, id) __PM_ItemChecked(PopupMenuBase, (pm), (id))

LONG __PM_GetItemAttrsA(__reg("a6") void *, __reg("a2") struct PopupMenu *item, __reg("a1") struct TagItem *tags)="\tjsr\t-66(a6)";
#define PM_GetItemAttrsA(item, tags) __PM_GetItemAttrsA(PopupMenuBase, (item), (tags))

#if !defined(NO_INLINE_STDARG) && (__STDC__ == 1L) && (__STDC_VERSION__ >= 199901L)
LONG __PM_GetItemAttrs(__reg("a6") void *, __reg("a2") struct PopupMenu *item, ...)="\tmove.l\ta1,-(a7)\n\tlea\t4(a7),a1\n\tjsr\t-66(a6)\n\tmovea.l\t(a7)+,a1";
#define PM_GetItemAttrs(...) __PM_GetItemAttrs(PopupMenuBase, __VA_ARGS__)
#endif

LONG __PM_SetItemAttrsA(__reg("a6") void *, __reg("a2") struct PopupMenu *item, __reg("a1") struct TagItem *tags)="\tjsr\t-72(a6)";
#define PM_SetItemAttrsA(item, tags) __PM_SetItemAttrsA(PopupMenuBase, (item), (tags))

#if !defined(NO_INLINE_STDARG) && (__STDC__ == 1L) && (__STDC_VERSION__ >= 199901L)
LONG __PM_SetItemAttrs(__reg("a6") void *, __reg("a2") struct PopupMenu *item, ...)="\tmove.l\ta1,-(a7)\n\tlea\t4(a7),a1\n\tjsr\t-72(a6)\n\tmovea.l\t(a7)+,a1";
#define PM_SetItemAttrs(...) __PM_SetItemAttrs(PopupMenuBase, __VA_ARGS__)
#endif

struct PopupMenu *__PM_FindItem(__reg("a6") void *, __reg("a1") struct PopupMenu *menu, __reg("d1") ULONG id)="\tjsr\t-78(a6)";
#define PM_FindItem(menu, id) __PM_FindItem(PopupMenuBase, (menu), (id))

/*--- functions in V5 or higher --- */

/* State changes */

void __PM_AlterState(__reg("a6") void *, __reg("a1") struct PopupMenu *menu, __reg("a2") struct PM_IDLst *idlst, __reg("d1") ULONG action)="\tjsr\t-84(a6)";
#define PM_AlterState(menu, idlst, action) __PM_AlterState(PopupMenuBase, (menu), (idlst), (action))

/*--- functions in V6 or higher --- */

/* Obsolete V6 FilterIMsg vector (returns NULL). Kept for FuncTab layout. */
/* Published client headers historically mis-labelled this bias as PM_FilterIMsgA; */
/* the real FilterIMsgA follows ExLstA below. */

struct PM_IDLst *__PM_ExLstA(__reg("a6") void *, __reg("a1") ULONG *id)="\tjsr\t-96(a6)";
#define PM_ExLstA(id) __PM_ExLstA(PopupMenuBase, (id))

#if !defined(NO_INLINE_STDARG) && (__STDC__ == 1L) && (__STDC_VERSION__ >= 199901L)
struct PM_IDLst *__PM_ExLst(__reg("a6") void *, ...)="\tmove.l\ta1,-(a7)\n\tlea\t4(a7),a1\n\tjsr\t-96(a6)\n\tmovea.l\t(a7)+,a1";
#define PM_ExLst(...) __PM_ExLst(PopupMenuBase, __VA_ARGS__)
#endif

APTR __PM_FilterIMsgA(__reg("a6") void *, __reg("a0") struct Window *window, __reg("a1") struct PopupMenu *menu, __reg("a2") struct IntuiMessage *imsg, __reg("a3") struct TagItem *tags)="\tjsr\t-102(a6)";
#define PM_FilterIMsgA(window, menu, imsg, tags) __PM_FilterIMsgA(PopupMenuBase, (window), (menu), (imsg), (tags))

#if !defined(NO_INLINE_STDARG) && (__STDC__ == 1L) && (__STDC_VERSION__ >= 199901L)
APTR __PM_FilterIMsg(__reg("a6") void *, __reg("a0") struct Window *window, __reg("a1") struct PopupMenu *menu, __reg("a2") struct IntuiMessage *imsg, ...)="\tmove.l\ta3,-(a7)\n\tlea\t4(a7),a3\n\tjsr\t-102(a6)\n\tmovea.l\t(a7)+,a3";
#define PM_FilterIMsg(...) __PM_FilterIMsg(PopupMenuBase, __VA_ARGS__)
#endif

/*--- functions in V8 or higher --- */

/* Dynamic menu editing */

LONG __PM_InsertMenuItemA(__reg("a6") void *, __reg("a0") struct PopupMenu *menu, __reg("a1") struct TagItem *tags)="\tjsr\t-108(a6)";
#define PM_InsertMenuItemA(menu, tags) __PM_InsertMenuItemA(PopupMenuBase, (menu), (tags))

#if !defined(NO_INLINE_STDARG) && (__STDC__ == 1L) && (__STDC_VERSION__ >= 199901L)
LONG __PM_InsertMenuItem(__reg("a6") void *, __reg("a0") struct PopupMenu *menu, ...)="\tmove.l\ta1,-(a7)\n\tlea\t4(a7),a1\n\tjsr\t-108(a6)\n\tmovea.l\t(a7)+,a1";
#define PM_InsertMenuItem(...) __PM_InsertMenuItem(PopupMenuBase, __VA_ARGS__)
#endif

struct PopupMenu *__PM_RemoveMenuItem(__reg("a6") void *, __reg("a0") struct PopupMenu *menu, __reg("a1") struct PopupMenu *item)="\tjsr\t-114(a6)";
#define PM_RemoveMenuItem(menu, item) __PM_RemoveMenuItem(PopupMenuBase, (menu), (item))

/*--- functions in V9 or higher --- */

/* Hooks, version, prefs, layout */

BOOL __PM_AbortHook(__reg("a6") void *, __reg("a0") APTR handle)="\tjsr\t-120(a6)";
#define PM_AbortHook(handle) __PM_AbortHook(PopupMenuBase, (handle))

STRPTR __PM_GetVersion(__reg("a6") void *)="\tjsr\t-126(a6)";
#define PM_GetVersion() __PM_GetVersion(PopupMenuBase)

void __PM_ReloadPrefs(__reg("a6") void *)="\tjsr\t-132(a6)";
#define PM_ReloadPrefs() __PM_ReloadPrefs(PopupMenuBase)

LONG __PM_LayoutMenuA(__reg("a6") void *, __reg("a0") struct Window *window, __reg("a1") struct PopupMenu *menu, __reg("a2") struct TagItem *tags)="\tjsr\t-138(a6)";
#define PM_LayoutMenuA(window, menu, tags) __PM_LayoutMenuA(PopupMenuBase, (window), (menu), (tags))

#if !defined(NO_INLINE_STDARG) && (__STDC__ == 1L) && (__STDC_VERSION__ >= 199901L)
LONG __PM_LayoutMenu(__reg("a6") void *, __reg("a0") struct Window *window, __reg("a1") struct PopupMenu *menu, ...)="\tmove.l\ta2,-(a7)\n\tlea\t4(a7),a2\n\tjsr\t-138(a6)\n\tmovea.l\t(a7)+,a2";
#define PM_LayoutMenu(...) __PM_LayoutMenu(PopupMenuBase, __VA_ARGS__)
#endif


/* Private ARexx host vector (FuncTab placeholder; not for applications) */

/*--- functions in V10 or higher --- */
void __PM_FreeIDList(__reg("a6") void *, __reg("a0") struct PM_IDLst *list)="\tjsr\t-150(a6)";
#define PM_FreeIDList(list) __PM_FreeIDList(PopupMenuBase, (list))


#endif /* INLINE_POPUPMENU_PROTOS_H */
