/*
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Copyright (C) 1996-2002 Henrik Isaksson
 * Copyright (C) 2026 amigazen project
 *
 * inline/popupmenu.h - Generated by LibDescConverter from SFD
 */

#ifndef INLINE_POPUPMENU_H
#define INLINE_POPUPMENU_H

/*
** GCC format inline files.
**
**
** Generated by LibDescConverter from an sfd file
*/

/*"popupmenu.library" */
/*--- functions in V2 or higher --- */

/* Menu and item construction */

#define PM_MakeMenuA(tags)    \
({  \
	register void *b __asm("a6") = PopupMenuBase;  \
	register struct TagItem *p0 __asm("a1") = (tags);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-30:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#ifndef NO_INLINE_STDARG
#define PM_MakeMenu(vargs...)    \
({  \
	ULONG _argarray[] = {vargs};   \
	PM_MakeMenuA(_argarray);   \
	r;   \
})
#endif

#define PM_MakeItemA(tags)    \
({  \
	register void *b __asm("a6") = PopupMenuBase;  \
	register struct TagItem *p0 __asm("a1") = (tags);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-36:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#ifndef NO_INLINE_STDARG
#define PM_MakeItem(vargs...)    \
({  \
	ULONG _argarray[] = {vargs};   \
	PM_MakeItemA(_argarray);   \
	r;   \
})
#endif

#define PM_FreePopupMenu(menu)    \
({  \
	register void *b __asm("a6") = PopupMenuBase;  \
	register struct PopupMenu *p0 __asm("a1") = (menu);   \
	__asm volatile ("jsr a6@(-42:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})

#define PM_OpenPopupMenuA(wnd, tags)    \
({  \
	register void *b __asm("a6") = PopupMenuBase;  \
	register struct Window *p0 __asm("a1") = (wnd);   \
	register struct TagItem *p1 __asm("a2") = (tags);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-48:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#ifndef NO_INLINE_STDARG
#define PM_OpenPopupMenu(wnd, vargs...)    \
({  \
	ULONG _argarray[] = {vargs};   \
	PM_OpenPopupMenuA((wnd), _argarray);   \
	r;   \
})
#endif

#define PM_MakeIDListA(tags)    \
({  \
	register void *b __asm("a6") = PopupMenuBase;  \
	register struct TagItem *p0 __asm("a1") = (tags);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-54:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#ifndef NO_INLINE_STDARG
#define PM_MakeIDList(vargs...)    \
({  \
	ULONG _argarray[] = {vargs};   \
	PM_MakeIDListA(_argarray);   \
	r;   \
})
#endif

/*--- functions in V3 or higher --- */

/* Item query and attributes */

#define PM_ItemChecked(pm, id)    \
({  \
	register void *b __asm("a6") = PopupMenuBase;  \
	register struct PopupMenu *p0 __asm("a1") = (pm);   \
	register ULONG p1 __asm("d1") = (id);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-60:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define PM_GetItemAttrsA(item, tags)    \
({  \
	register void *b __asm("a6") = PopupMenuBase;  \
	register struct PopupMenu *p0 __asm("a2") = (item);   \
	register struct TagItem *p1 __asm("a1") = (tags);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-66:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#ifndef NO_INLINE_STDARG
#define PM_GetItemAttrs(item, vargs...)    \
({  \
	ULONG _argarray[] = {vargs};   \
	PM_GetItemAttrsA((item), _argarray);   \
	r;   \
})
#endif

#define PM_SetItemAttrsA(item, tags)    \
({  \
	register void *b __asm("a6") = PopupMenuBase;  \
	register struct PopupMenu *p0 __asm("a2") = (item);   \
	register struct TagItem *p1 __asm("a1") = (tags);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-72:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#ifndef NO_INLINE_STDARG
#define PM_SetItemAttrs(item, vargs...)    \
({  \
	ULONG _argarray[] = {vargs};   \
	PM_SetItemAttrsA((item), _argarray);   \
	r;   \
})
#endif

#define PM_FindItem(menu, id)    \
({  \
	register void *b __asm("a6") = PopupMenuBase;  \
	register struct PopupMenu *p0 __asm("a1") = (menu);   \
	register ULONG p1 __asm("d1") = (id);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-78:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

/*--- functions in V5 or higher --- */

/* State changes */

#define PM_AlterState(menu, idlst, action)    \
({  \
	register void *b __asm("a6") = PopupMenuBase;  \
	register struct PopupMenu *p0 __asm("a1") = (menu);   \
	register struct PM_IDLst *p1 __asm("a2") = (idlst);   \
	register ULONG p2 __asm("d1") = (action);   \
	__asm volatile ("jsr a6@(-84:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})

/*--- functions in V6 or higher --- */

/* Obsolete V6 FilterIMsg vector (returns NULL). Kept for FuncTab layout. */
/* Published client headers historically mis-labelled this bias as PM_FilterIMsgA; */
/* the real FilterIMsgA follows ExLstA below. */

#define PM_ExLstA(id)    \
({  \
	register void *b __asm("a6") = PopupMenuBase;  \
	register ULONG *p0 __asm("a1") = (id);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-96:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#ifndef NO_INLINE_STDARG
#define PM_ExLst(vargs...)    \
({  \
	ULONG _argarray[] = {vargs};   \
	PM_ExLstA(_argarray);   \
	r;   \
})
#endif

#define PM_FilterIMsgA(window, menu, imsg, tags)    \
({  \
	register void *b __asm("a6") = PopupMenuBase;  \
	register struct Window *p0 __asm("a0") = (window);   \
	register struct PopupMenu *p1 __asm("a1") = (menu);   \
	register struct IntuiMessage *p2 __asm("a2") = (imsg);   \
	register struct TagItem *p3 __asm("a3") = (tags);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-102:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2), "r"(p3) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#ifndef NO_INLINE_STDARG
#define PM_FilterIMsg(window, menu, imsg, vargs...)    \
({  \
	ULONG _argarray[] = {vargs};   \
	PM_FilterIMsgA((window), (menu), (imsg), _argarray);   \
	r;   \
})
#endif

/*--- functions in V8 or higher --- */

/* Dynamic menu editing */

#define PM_InsertMenuItemA(menu, tags)    \
({  \
	register void *b __asm("a6") = PopupMenuBase;  \
	register struct PopupMenu *p0 __asm("a0") = (menu);   \
	register struct TagItem *p1 __asm("a1") = (tags);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-108:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#ifndef NO_INLINE_STDARG
#define PM_InsertMenuItem(menu, vargs...)    \
({  \
	ULONG _argarray[] = {vargs};   \
	PM_InsertMenuItemA((menu), _argarray);   \
	r;   \
})
#endif

#define PM_RemoveMenuItem(menu, item)    \
({  \
	register void *b __asm("a6") = PopupMenuBase;  \
	register struct PopupMenu *p0 __asm("a0") = (menu);   \
	register struct PopupMenu *p1 __asm("a1") = (item);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-114:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

/*--- functions in V9 or higher --- */

/* Hooks, version, prefs, layout */

#define PM_AbortHook(handle)    \
({  \
	register void *b __asm("a6") = PopupMenuBase;  \
	register APTR p0 __asm("a0") = (handle);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-120:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define PM_GetVersion()    \
({  \
	register void *b __asm("a6") = PopupMenuBase;  \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-126:W);" : "+r"(b), "=r"(r) :  : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define PM_ReloadPrefs()    \
({  \
	register void *b __asm("a6") = PopupMenuBase;  \
	__asm volatile ("jsr a6@(-132:W);" : "+r"(b), "=r"(r) :  : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})

#define PM_LayoutMenuA(window, menu, tags)    \
({  \
	register void *b __asm("a6") = PopupMenuBase;  \
	register struct Window *p0 __asm("a0") = (window);   \
	register struct PopupMenu *p1 __asm("a1") = (menu);   \
	register struct TagItem *p2 __asm("a2") = (tags);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-138:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#ifndef NO_INLINE_STDARG
#define PM_LayoutMenu(window, menu, vargs...)    \
({  \
	ULONG _argarray[] = {vargs};   \
	PM_LayoutMenuA((window), (menu), _argarray);   \
	r;   \
})
#endif


/* Private ARexx host vector (FuncTab placeholder; not for applications) */

/*--- functions in V10 or higher --- */
#define PM_FreeIDList(list)    \
({  \
	register void *b __asm("a6") = PopupMenuBase;  \
	register struct PM_IDLst *p0 __asm("a0") = (list);   \
	__asm volatile ("jsr a6@(-150:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})


#endif /* INLINE_POPUPMENU_H */
