/*
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Copyright (C) 1996-2002 Henrik Isaksson
 * Copyright (C) 2026 amigazen project
 *
 * clib/popupmenu_protos.h - Generated by LibDescConverter from SFD
 */

#ifndef CLIB_POPUPMENU_PROTOS_H
#define CLIB_POPUPMENU_PROTOS_H

/*
** 'C' prototypes. For use with 32 bit integers only.
**
**
** Generated by LibDescConverter from an sfd file
*/

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif
#ifndef INTUITION_INTUITION_H
#include <intuition/intuition.h>
#endif
#ifndef LIBRARIES_PM_H
#include <libraries/pm.h>
#endif

/*"popupmenu.library"*/
/*--- functions in V2 or higher ---*/

/* Menu and item construction*/

struct PopupMenu *PM_MakeMenuA(struct TagItem *tags);
struct PopupMenu *PM_MakeMenu(Tag firstTag, ...);
struct PopupMenu *PM_MakeItemA(struct TagItem *tags);
struct PopupMenu *PM_MakeItem(Tag firstTag, ...);
void PM_FreePopupMenu(struct PopupMenu *menu);
ULONG PM_OpenPopupMenuA(struct Window *wnd, struct TagItem *tags);
ULONG PM_OpenPopupMenu(struct Window *wnd, ...);
struct PM_IDLst *PM_MakeIDListA(struct TagItem *tags);
struct PM_IDLst *PM_MakeIDList(Tag firstTag, ...);
/*--- functions in V3 or higher ---*/

/* Item query and attributes*/

BOOL PM_ItemChecked(struct PopupMenu *pm, ULONG id);
LONG PM_GetItemAttrsA(struct PopupMenu *item, struct TagItem *tags);
LONG PM_GetItemAttrs(struct PopupMenu *item, ...);
LONG PM_SetItemAttrsA(struct PopupMenu *item, struct TagItem *tags);
LONG PM_SetItemAttrs(struct PopupMenu *item, ...);
struct PopupMenu *PM_FindItem(struct PopupMenu *menu, ULONG id);
/*--- functions in V5 or higher ---*/

/* State changes*/

void PM_AlterState(struct PopupMenu *menu, struct PM_IDLst *idlst, ULONG action);
/*--- functions in V6 or higher ---*/

/* Obsolete V6 FilterIMsg vector (returns NULL). Kept for FuncTab layout.*/
/* Published client headers historically mis-labelled this bias as PM_FilterIMsgA;*/
/* the real FilterIMsgA follows ExLstA below.*/

struct PM_IDLst *PM_ExLstA(ULONG *id);
struct PM_IDLst *PM_ExLst(Tag firstTag, ...);
APTR PM_FilterIMsgA(struct Window *window, struct PopupMenu *menu, struct IntuiMessage *imsg, struct TagItem *tags);
APTR PM_FilterIMsg(struct Window *window, struct PopupMenu *menu, struct IntuiMessage *imsg, ...);
/*--- functions in V8 or higher ---*/

/* Dynamic menu editing*/

LONG PM_InsertMenuItemA(struct PopupMenu *menu, struct TagItem *tags);
LONG PM_InsertMenuItem(struct PopupMenu *menu, ...);
struct PopupMenu *PM_RemoveMenuItem(struct PopupMenu *menu, struct PopupMenu *item);
/*--- functions in V9 or higher ---*/

/* Hooks, version, prefs, layout*/

BOOL PM_AbortHook(APTR handle);
STRPTR PM_GetVersion(void);
void PM_ReloadPrefs(void);
LONG PM_LayoutMenuA(struct Window *window, struct PopupMenu *menu, struct TagItem *tags);
LONG PM_LayoutMenu(struct Window *window, struct PopupMenu *menu, ...);

/* Private ARexx host vector (FuncTab placeholder; not for applications)*/

/*--- functions in V10 or higher ---*/
void PM_FreeIDList(struct PM_IDLst *list);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CLIB_POPUPMENU_PROTOS_H */
